### ISSUE TITLE
Список всех незакрытых задач

### ISSUE THREAD

**Issue by Kotlyarov-ab** [redcyb/issue_tracker_bot#10]
Добавить возможность вызвать список всех незакрытых задач с указанием номеров машин

**Comment by redcyb** [comment]
Это будет относительно дорогой по времени запрос (до 2 минут при полном наборе устройств), поскольку есть ограничение на рейт запросов в гугл докс. Надо подумать, как ускорить. МБ доп БД, или еще что

**Comment by redcyb** [comment]
implemented and closed
