### ISSUE TITLE
Списки типовых неисправностей и методов устранения

### ISSUE THREAD

**Issue by Kotlyarov-ab** [redcyb/issue_tracker_bot#4]
Добавить возможность выбрать одну/несколько типовых неисправностей при заполнении "проблемы"
аналогично добавить возможность выбрать одно/несколько типовых действий по устранению неисправности в "решение"
оставить возможность ввести произвольный текст, на случай возникновения нетипичной проблемы

**Comment by redcyb** [comment]
added in this PR
https://github.com/redcyb/issue_tracker_bot/pull/16
